spring.application.name=padelNews

# ===== Serveur HTTP =====
server.port=8082

# ===== PostgreSQL Database (Docker) - Désactivé =====
# spring.datasource.url=jdbc:postgresql://localhost:5440/padelService
# spring.datasource.username=padel
# spring.datasource.password=padel
# spring.datasource.driver-class-name=org.postgresql.Driver

# ===== H2 Database (In-Memory) =====
spring.datasource.url=jdbc:h2:mem:padeldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ===== Propriétés communes =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.main.allow-bean-definition-overriding=true

# ===== JWT Configuration =====
jwt.secret=02c477941249bfd9b6639683ae9ed1a2e8d5cb08b2ec8d96f9c83d1434613bb5
jwt.expiration=86400000

# ===== Swagger / OpenAPI Configuration =====
springdoc.api-docs.path=/api-docs/v3/api-docs
springdoc.swagger-ui.path=/api-docs/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
