
# ===== Database (PostgreSQL Docker) =====
spring.datasource.url=jdbc:postgresql://localhost:5440/padelService
spring.datasource.username=padel
spring.datasource.password=padel
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.allow-bean-definition-overriding=true

# ===== Server =====
server.port=8080

# ===== JWT Configuration =====
jwt.secret=02c477941249bfd9b6639683ae9ed1a2e8d5cb08b2ec8d96f9c83d1434613bb5
jwt.expiration=86400000

# ===== Swagger / OpenAPI Configuration =====
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha


# ===== H2 Console (désactivée) =====
spring.h2.console.enabled=false
